version: '3'
services:
  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - './app/public:/var/www/html'

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - './app/public:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

  db:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
